### ISSUE TITLE
Missing Scripts Directory

### ISSUE THREAD

**Issue by ericleong** [OstrichProjects/typechime.js#1]
It looks like the scripts directory is missing. This is the error I got:

```
Error: C:\Users\Eric\Documents\GitHub\typechime.js\views\home\index.jade:17
    15|     a(href="/about") About typeChi.me
    16|
  > 17|   include scripts
    18|

ENOENT, no such file or directory 'C:\Users\Eric\Documents\GitHub\typechime.js\views\home\scripts.jade'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Parser.parseInclude (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:585:18)
    at Parser.parseExpr (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:223:21)
    at Parser.block (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:708:25)
    at Parser.parseBlock (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:514:14)
    at Parser.parseExpr (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:215:21)
    at Parser.parse (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\parser.js:122:25)
    at parse (C:\Users\Eric\Documents\GitHub\typechime.js\node_modules\jade\lib\index.js:104:21)
```

**Comment by jonathan-ostrander** [comment]
Poop.  Fixed.
